name: Build and Release Godot Game

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  export:
    name: Export
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # platform: [windows, linux, web]
        platform: [win]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      
      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v1
        with:
          version: 4.4.1
          use-dotnet: false
      
      - name: Export Game
        id: export
        uses: firebelley/godot-export@v5.2.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot-builds/releases/download/4.2-stable/Godot_v4.2-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: exports-${{ matrix.platform }}
          path: ${{ steps.export.outputs.archive-directory }}/*.zip
      
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.export.outputs.archive-directory }}/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
