name: Build and Release Godot Game

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      build_targets:
        description: 'Build desktop targets?'
        required: false
        default: 'true'
      deploy_pages:
        description: 'Deploy to GitHub Pages?'
        required: false
        default: 'true'

jobs:
  export_game:
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.build_targets == 'true' }}
    runs-on: ubuntu-latest
    permissions: write-all
    name: Export Game (Desktop)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Export game
        id: export
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot-builds/releases/download/4.4.1-stable/Godot_v4.4.1-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true
          presets_to_export: 'win, linux'

      - name: Create release
        uses: ncipollo/release-action@v1.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          tag: ${{ github.ref_name }}
          artifacts: ${{ steps.export.outputs.archive_directory }}/*

  export_web:
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.deploy_pages == 'true' }}
    runs-on: ubuntu-latest
    name: Export Web (HTML5)
    container:
      image: barichello/godot-ci:4.4.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup export templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/4.4.1.stable ~/.local/share/godot/export_templates/4.4.1.stable

      - name: Web Build
        run: |
          mkdir -p build/web
          godot --headless --verbose --export-release "web" "build/web/index.html"

      - name: Upload Web Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web
          path: build/web
          retention-days: 1

      - name: Rsync Deploy (if configured)
        if: ${{ secrets.REMOTE_HOST != '' && secrets.REMOTE_USER != '' }}
        uses: burnett01/rsync-deployments@v1.4.0
        with:
          switches: -avzr --delete
          path: build/web/
          remote_path: /path/to/remote/directory
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages
          destination_dir: web
          keep_files: false
          force_orphan: true
          commit_message: 'Deploy to GitHub Pages'
          allow_empty_commit: true
